export interface Entity {}
export interface Iterable {}
export interface HashMap {}
export interface EnumFacing {}
export interface NBTTagCompound {}
export interface BlockPos.MutableBlockPos {}
export interface WorldServer {}
export interface EventBus {}
export interface Logger {}
export interface World {}
export interface TileEntity {}
export interface Container {}
export interface Consumer {}
export interface List {}
export interface Supplier {}
export interface Queue {}
export interface IInventory {}
export interface DamageSource {}
export interface InventoryEnderChest {}
export interface ImmutableMap {}
export interface InventoryPlayer {}
export interface IntHashMap.Entry {}
export interface Collection {}
export interface Block {}
export interface BlockPos.PooledMutableBlockPos {}
export interface Event {}
export interface Slot {}
export interface Class {}
export interface INpc {}
export interface ItemStack {}
export interface File {}
export interface Map {}
