export interface Entity {}
export interface HashMap {}
export interface NBTTagCompound {}
export interface WorldServer {}
export interface EventBus {}
export interface World {}
export interface TileEntity {}
export interface Container {}
export interface T {}
export interface Consumer {}
export interface V {}
export interface List {}
export interface Supplier {}
export interface Boolean {}
export interface Queue {}
export interface IInventory {}
export interface DamageSource {}
export interface InventoryEnderChest {}
export interface ImmutableMap {}
export interface Integer {}
export interface InventoryPlayer {}
export interface Float {}
export interface Collection {}
export interface Block {}
export interface Event {}
export interface Slot {}
export interface short {}
export interface Class {}
export interface INpc {}
export interface ItemStack {}
export interface File {}
export interface Map {}
